# Generated by Django 4.1.9 on 2023-05-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.ImageField(blank=True, null=True, upload_to="users/photos"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32, verbose_name="Phone Number"),
        ),
    ]
