# Generated by Django 4.1.9 on 2023-05-24 13:23

import devteamtask.utils.projects
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Daily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("note", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily",
                "verbose_name_plural": "Daily",
            },
        ),
        migrations.CreateModel(
            name="EventNotes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("planning", models.TextField(blank=True, null=True)),
                ("review", models.TextField(blank=True, null=True)),
                ("retrospective", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Event notes",
                "verbose_name_plural": "Event notes",
                "db_table": "event_notes",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("expires", models.DateTimeField(default=devteamtask.utils.projects.in_three_days)),
                ("token", models.CharField(default=devteamtask.utils.projects.get_url, max_length=24)),
            ],
            options={
                "verbose_name": "Invite",
                "verbose_name_plural": "Invites",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("start_data", models.DateField(auto_now_add=True)),
                ("end_data", models.DateField()),
                (
                    "state",
                    models.CharField(choices=[("1", "IN_PROGRESS"), ("2", "FINISHED")], default="1", max_length=2),
                ),
                ("logo_url", models.ImageField(blank=True, null=True, upload_to="projects/logo")),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=24)),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=24)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
