# Generated by Django 4.1.9 on 2023-05-10 00:39

import devteamtask.utils.projects
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField()),
                (
                    "state",
                    models.CharField(choices=[("1", "IN_PROGRESS"), ("2", "FINISHED")], default="1", max_length=2),
                ),
            ],
            options={
                "verbose_name": "Sprint",
                "verbose_name_plural": "Sprints",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=24)),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=24)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("start_data", models.DateField(auto_now_add=True)),
                ("end_data", models.DateField()),
                (
                    "state",
                    models.CharField(choices=[("1", "IN_PROGRESS"), ("2", "FINISHED")], default="1", max_length=2),
                ),
                ("collaborators", models.ManyToManyField(related_name="collaborators", to=settings.AUTH_USER_MODEL)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="leader", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "product_onwer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_onwer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("sprints", models.ManyToManyField(related_name="sprints", to="projects.sprint")),
                ("status", models.ManyToManyField(related_name="status", to="projects.status")),
                ("tags", models.ManyToManyField(related_name="tags", to="projects.tag")),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("expires", models.DateTimeField(default=devteamtask.utils.projects.in_three_days)),
                ("link", models.CharField(default=devteamtask.utils.projects.get_url, max_length=24)),
                ("project_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project")),
                (
                    "user_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="user_group", to="auth.group"
                    ),
                ),
            ],
            options={
                "verbose_name": "Invite",
                "verbose_name_plural": "Invites",
            },
        ),
    ]
