# Generated by Django 4.1.9 on 2023-05-24 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(blank=True, related_name="collaborators", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="project",
            name="event_notes",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="projects.eventnotes"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="leader", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="product_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.ManyToManyField(blank=True, related_name="status", to="projects.status"),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="tags", to="projects.tag"),
        ),
        migrations.AddField(
            model_name="invite",
            name="project_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
        ),
        migrations.AddField(
            model_name="invite",
            name="user_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="user_group", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="daily",
            name="event_notes_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="projects.eventnotes"),
        ),
    ]
