# Generated by Django 4.1.9 on 2023-05-10 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(blank=True, related_name="collaborators", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="project",
            name="product_onwer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_onwer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sprints",
            field=models.ManyToManyField(blank=True, related_name="sprints", to="projects.sprint"),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.ManyToManyField(blank=True, related_name="status", to="projects.status"),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="tags", to="projects.tag"),
        ),
    ]
