# Generated by Django 4.1.9 on 2023-07-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="project_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
        ),
        migrations.AddField(
            model_name="tasks",
            name="sprint_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.sprint"
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="status",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="projects.status"),
        ),
        migrations.AddField(
            model_name="tasks",
            name="tag",
            field=models.ManyToManyField(blank=True, to="projects.tag"),
        ),
        migrations.AddField(
            model_name="sprint",
            name="project_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
