# Generated by Django 4.1.9 on 2023-05-24 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="task_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="project_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
        ),
        migrations.AddField(
            model_name="tasks",
            name="sprint_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.sprint"
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="status",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="projects.status"),
        ),
        migrations.AddField(
            model_name="tasks",
            name="tag",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="projects.tag"
            ),
        ),
        migrations.AddField(
            model_name="sprint",
            name="project_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
