# Generated by Django 4.0.8 on 2023-05-11 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.tag'),
        ),
    ]
